name: GitHub metrics as SVG image
on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: "master"}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Setup a personal token in your secrets.
          token: ${{ secrets.METRICS_TOKEN }}
          # You can also setup a bot token for commits
          # committer_token: ${{ secrets.METRICS_BOT_TOKEN }}

          # Options
          user: hp77-creator
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_followup: yes
